### ISSUE TITLE
JavaFX imports not working

### ISSUE THREAD

**Issue by Its-Lachie** [Its-Lachie/Assignment1#3]
I get this error message on all imports except for FXML, and it will not run.

> The package javafx.application is accessible from more than one module: <unnamed>, javafx.graphics

And the console when running the maven build as clean javafx:run

> [INFO] Compiling 1 source file to C:\Users\lachy\eclipse-workspace\TextEditor-Assign1\target\classes
> [INFO] 
> [INFO] <<< javafx-maven-plugin:0.0.4:run (default-cli) < process-classes @ TextEditor-Assign1 <<<
> [INFO] 
> [INFO] 
> [INFO] --- javafx-maven-plugin:0.0.4:run (default-cli) @ TextEditor-Assign1 ---
> [WARNING] Can't extract module name from javafx-base-14-win.jar: Unsupported major.minor version 55.0
> [WARNING] Can't extract module name from javafx-graphics-14-win.jar: Unsupported major.minor version 55.0
> [WARNING] Can't extract module name from javafx-controls-14-win.jar: Unsupported major.minor version 55.0
> [WARNING] Some dependencies encountered issues while attempting to be resolved as modules and will not be included in the classpath; you can change this behavior via the  'includePathExceptionsInClasspath' configuration parameter.
> Error: --add-modules requires modules to be specified
> [ERROR] Command execution failed.
> org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
> 	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
> 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
> 	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:504)
> 	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:394)
> 	at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:100)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
> org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
> 	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
> 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
> 	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:504)
> 	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:394)
> 	at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:100)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  3.098 s
> [INFO] Finished at: 2020-08-24T22:25:31+12:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.openjfx:javafx-maven-plugin:0.0.4:run (default-cli) on project TextEditor-Assign1: Error: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
>

**Comment by Its-Lachie** [comment]
Found the issue, it was with the dependencies in the pom.xml file, specifically this:

```
<dependencies>
  <dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-controls</artifactId>
    <version>14</version>
  </dependency>
</dependencies>
```

Issue is now resolved, but still getting Invocation error
